
substitutions:
  name: jahody


preferences:
  flash_write_interval: 30s

esphome:
  name: $name
  on_boot:
    then:
      - ds1307.read_time:
      - delay: 180s
      - if:
          condition:
            lambda: |-
                return (id(hour).state == -1);
          then:
              - logger.log: "periodic pump disabled, sleep for 1h..."
              - deep_sleep.enter:
                  id: deep_sleep_1
                  sleep_duration: 1h
          else:

            # tady je potreba ntp vymenit za rtc
            # a po prvnim synchronizacnim bootu znova rebootnout

            - if:
                condition:
                    lambda: |-
                        return (id(rtc).utcnow().is_valid() && id(rtc).utcnow().timestamp > 1680000000) && (id(rtc).utcnow().timestamp - id(last_pump_ts).state > 60*60*20) && (id(rtc).utcnow().hour >= id(hour).state);
                then:
                    - number.set:
                        id: last_pump_ts 
                        value: !lambda |-
                                  return id(rtc).utcnow().timestamp;
                    - delay: 40s # flush
                    - logger.log: "periodic action!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!..."
                    - switch.turn_on: periodic_pump1
                    
                    # delka zalevani s/min/h
                    - delay: !lambda |-
                                    return id(pump_length).state * 1000;
                    
                    - logger.log: "periodic action offfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..."
                    - switch.turn_off: periodic_pump1
                    - logger.log: "sleep for 20h..."
                    - deep_sleep.enter:
                            id: deep_sleep_1
                            #sleep_duration: !lambda |-
                            #  return 20*60*60
                            sleep_duration: 20h
                else:
                    - logger.log: "nothing to do yet, sleep..."
                    - deep_sleep.enter:
                        id: deep_sleep_1
                        sleep_duration: 2h




esp32:
  board: nodemcu-32s


wifi:
  networks:
  - ssid: !secret ssid1
    password: !secret password1

  - ssid: !secret ssid2
    password: !secret password2

  - ssid: !secret ssid3
    password: !secret password3


  reboot_timeout: 1h
  
  
mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password



ota:
  safe_mode: false
  password: ""

logger:

captive_portal:
    
web_server:
  port: 80
  ota: true



sensor:
  - platform: uptime
    name: Uptime Sensor

  - platform: wifi_signal
    name: "Irrigation Wifi"
    update_interval: 60s
    
  - platform: sun
    name: Sun Elevation
    type: elevation
  - platform: sun
    name: Sun Azimuth
    type: azimuth


      
light:
  - platform: status_led
    name: "status LED(pin2)"
    id: status
    pin: 2

      
switch:
  - platform: gpio
    pin: 18
    id: periodic_pump1
    name: "periodic_pump1"
    inverted: true
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 19
    id: periodic_pump2
    name: "periodic_pump2"
    inverted: true
    restore_mode: ALWAYS_OFF

  - platform: restart
    id: manual_restart
    name: "Living Room Restart"




binary_sensor:
  - platform: gpio
    id: button32
    pin: 
      inverted: true
      number: 32
      mode: 
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.turn_off: periodic_pump1
        - logger.log: "..."

  - platform: gpio
    id: button33
    pin: 
      inverted: true
      number: 33
      mode: 
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.turn_on: periodic_pump1
        - logger.log: "..."

  - platform: gpio
    id: button35
    pin: 
      inverted: true
      number: 26
      mode: 
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.turn_on: periodic_pump2
        - logger.log: "..."

  - platform: gpio
    id: button34
    pin: 
      inverted: true
      number: 27
      mode: 
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.turn_off: periodic_pump2
        - logger.log: "..."



output:
  - platform: gpio
    pin: 25
    id: tlacitek


sun:
  latitude: 50.0755°
  longitude: 14.4378°

  on_sunrise:
    - then:
        - logger.log: Good morning!
  on_sunset:
    - then:
        - logger.log: Good evening!




# display sun values in gui        
text_sensor:
  - platform: sun
    name: Next Sunrise
    type: sunrise
  - platform: sun
    name: Next Sunset
    type: sunset
  - platform: template
    name: "Time NTP"
    lambda: |-
      char str[30];
      if (!id(ntp).now().is_valid()) { return { "----" }; }
      time_t currTime = id(ntp).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
      //strftime(str, sizeof(str), "%c", localtime(&currTime));
      return  { str };
    update_interval: 5s
  - platform: template
    name: "Time RTC"
    lambda: |-
      char str[30];
      time_t currTime = id(rtc).now().timestamp;
      strftime(str, sizeof(str), "%Y-%m-%d %H:%M:%S", localtime(&currTime));
      //strftime(str, sizeof(str), "%c", localtime(&currTime));
      return  { str };
    update_interval: 5s





        
time:  # https://esphome.io/components/time/ds1307.html#ds1307-config-example

  - platform: ds1307
    id: rtc
    update_interval: never

  
  - platform: sntp
    id: ntp
    #timezone: Europe/Prague
    on_time_sync:
      then:
        - logger.log: "rtc.write_time..."
        - ds1307.write_time
        - logger.log: "Synchronized clock."



deep_sleep:
#  wakeup_pin: 32
  id: deep_sleep_1



i2c:
#  sda: 21
#  scl: 22
  scan: true
  id: bus_a



number:
  
  - platform: template
    id: hour
    name: "pump hour"
    min_value: -1
    max_value: 23
    step: 1
    restore_value: true
    
    # defaultni hodnota
    initial_value: 18 # military time (8 vecer letni cas praha/evropa)

    optimistic: true
  
  - platform: template
    id: last_pump_ts
    name: "last_pump_ts"
    min_value: 0
    max_value: 3360287004
    step: 1
    restore_value: true
    initial_value: 0
    optimistic: true

  - platform: template
    id: pump_length
    name: "pump_length"
    min_value: 3
    max_value: 3000
    initial_value: 60
    step: 1
    restore_value: true
    optimistic: true



